server:
  port: 8080
  servlet:
    contextPath: /MovieWatchlistAPI/1.0.0

spring:
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

springfox:
  documentation:
    open-api:
      v3:
        path: =/api-docs
